### PR TITLE
Major Style Update

### LINKED ISSUE #14: Background and foreground colors do not have a sufficient contrast ratio
Failing Elements
--
a.home
a.posts.active
a.timeline
a.repo
a.editor
a.README
h3.center
p.center
h5

I would change these elements.

### PR DESCRIPTION
**Pull request by BD103**
I'm adjusting and touching up the website to be visually pleasing, though I must admit. I may be re-writing the whole entire website...
Anywho, we'll see what happens. :D

### CODE REVIEW

**Comment by darkdarcool** [comment]
I think it looks good, but I think we are going to leave the css alone because we want the site to be very vibrant.

**Comment by BD103** [comment]
> I think it looks good, but I think we are going to leave the css alone because we want the site to be very vibrant.

Very vibrant? That's not _very vibrant_, it is eye-burning. I can make the style more insane, but I want to at least make it uniform.

**Review by darkdarcool — COMMENTED** [review]
Can you make it so that it would go to feature? Not main

**Comment by BD103** [comment]
> Can you make it so that it would go to feature? Not main

What's wrong with main? I looked over the other pr, but the comments didn't make sense.

**Comment by BD103** [comment]
> Can you make it so that it would go to feature? Not main

Ok. I did it. @darkdarcool

**Comment by whippingdot** [comment]
@BD103 all you changed was the background, right? I like the lighter background. There are some more changes to be done though.

**Comment by whippingdot** [comment]
I am sorry but I personally do not like this style update. It does not look good. Also home page is broken and it never loads. You said contribution when the README, repl, and Repo are not for contributing, they are just for looking. I personally like my CSS better, but you can make slight changes to that. This does not look nice. ~~this also messed up a lot of files~~ but one thing to note is I like where if you hover over the contributions it shows you the other options. I think we should keep that but it shouldn't be called contributions, it should be called more, and it should still be in the right side. Implement this **not** in a pr but in the feature branch itself

**Comment by whippingdot** [comment]
I will not delete the branch for now because @BD103 might need some CSS files for the animation

**Comment by BD103** [comment]
Ok. You don't like it. That's fine. What do you want me to change? Be specific. I can change color scheme, styles, fonts, etc. The general layout is harder, but possible. Also, I tried to get this out _before_ you guys started contributing a lot of the backend, but obviously I failed. What can I change to make it look better and more professional?

**Comment by whippingdot** [comment]
No, I don't like the whole theme. I don't like the purple color on the website mainly, and I think it looks too formal. I like our fonts and color scheme. The only thing I think we should implement in the feature branch is the hover button which shows more menu. I LOVE ♥ that feature and I think we should implement it. Tho I still think the hover thing should be on the right side. I tried implementing it but I failed, miserably.

**Comment by BD103** [comment]
Ohhhhhhh. Let me do some epic styling, and I'll be back.

**Comment by BD103** [comment]
Ok guys! We are back on track! @whippingdot please review, thanks. I changes fonts, gave animations, new color pallette, and removed the purple. I couldn't add any rounded borders unfortunately, because it would've looked weird. If you approve this, I won't immediately merge. I still want to merge some changes to this branch, then edit again to make it look good.

**Comment by whippingdot** [comment]
K, seems you were online 30 mins ago, hope you are still on. I will review quickly

**Comment by whippingdot** [comment]
love it @BD103 but going to have to edit it. When you wake up today, and when you start coding don't code in your repl, as I might've not pushed changes. Code [here](https://repl.it/@Whippingdot/Replit-2021#package.json).

**Comment by BD103** [comment]
Ok. I got it. You want me to add the latest features from feature?

**Comment by whippingdot** [comment]
> Ok. I got it. You want me to add the latest features from feature?

No no no, I just said that I might make changes to your thing. I still need to, but i can do it later. Finish everything you need to do, I will make my final changes tomorrow, and then you can merge and delete the branch tomorrow.

**Comment by whippingdot** [comment]
Also tomorrow I will fix the merge conflicts

**Comment by BD103** [comment]
#2 https://github.com/Repl-it-Coders/Repl.it-2020/pull/2#issuecomment-756133246

Check for list of things to do

**Comment by whippingdot** [comment]
hey @Repl-it-Coders/web-dev  I am changing the tags. I have a set of tags I always use so I am changing the tags to that. You can check out my tags at the repos in my other org @CoderBoiis

**Comment by zplusfour** [comment]
wait yall are using repl to push and commit and to do pr(s)?
I only use VSCode to do that idk why.
And yeah the reason that REPL IS LAGGY AND BUGGY

**Comment by ColePete** [comment]
@whippingdot, I got good news and bad news, which you wanna hear first?

**Comment by whippingdot** [comment]
> @whippingdot, I got good news and bad news, which you wanna hear first?

Bad news.
`MY FAV THING IN THE WORLD IS BAD NEWS` - Sanjaay R*******

**Comment by whippingdot** [comment]
> wait yall are using repl to push and commit and to do pr(s)?
> I only use VSCode to do that idk why.
> And yeah the reason that REPL IS LAGGY AND BUGGY

I sometimes use vs code(the reason for .vscode file) and that is because I want prettier to take effect and I want the spell checker to see the words I misspelled.

**Comment by ColePete** [comment]
@whippingdot well... the bad news is that I just tested positive for COVID this morning. 
The good news is that 
A. I feel fine 
B. You have all of my attention (MINUS ONLINE CLASSES) for coding 
C. I "get" to stay in my room all day. 
Soo... I will be VERY bored, so if you have anything I can help with let me know!

**Comment by whippingdot** [comment]
> @whippingdot well... the bad news is that I just tested positive for COVID this morning.
> The good news is that
> A. I feel fine
> B. You have all of my attention (MINUS ONLINE CLASSES) for coding
> C. I "get" to stay in my room all day.
> Soo... I will be VERY bored, so if you have anything I can help with let me know!

WHAT??!!! YOU HAVE COVID. BRUH... I don't think you shud code, I think you shud take rest or do whatever people with covid do. Take care.

**Comment by BD103** [comment]
> @whippingdot well... the bad news is that I just tested positive for COVID this morning.
> The good news is that
> A. I feel fine
> B. You have all of my attention (MINUS ONLINE CLASSES) for coding
> C. I "get" to stay in my room all day.
> Soo... I will be VERY bored, so if you have anything I can help with let me know!

Yeah. I agree with Whippingdot. I hope your health improves 😄

**Comment by zplusfour** [comment]
> @whippingdot well... the bad news is that I just tested positive for COVID this morning.
> The good news is that
> A. I feel fine
> B. You have all of my attention (MINUS ONLINE CLASSES) for coding
> C. I "get" to stay in my room all day.
> Soo... I will be VERY bored, so if you have anything I can help with let me know!

Aw, take care of yourself 💉 🌳

**Comment by zplusfour** [comment]
**NOTE**: Please, I saw some unmeanful commits names, please write a good name for the commit, and explain what'd you changed, this is github!

example: @whippingdot commited 12 hours ago: **Don't know what changed**
why you commited then?

**Comment by ColePete** [comment]
> WHAT??!!! YOU HAVE COVID. BRUH... I don't think you shud code, I think you shud take rest or do whatever people with covid do. Take care.

Nah, bro, I feel fine. I don't need to rest. Plus, coding isn't that hard on your body. It only hurts your head because of how frustrating it is.

**Comment by whippingdot** [comment]
> **NOTE**: Please, I saw some unmeanful commits names, please write a good name for the commit, and explain what'd you changed, this is github!
> 
> example: @whippingdot commited 12 hours ago: **Don't know what changed**
> why you commited then?

But I really didn't know what changed bro...I wanted to switch to a different branch so I **had** to commit. Sry

**Comment by zplusfour** [comment]
> But I really didn't know what changed bro...I wanted to switch to a different branch so I **had** to commit. Sry

you can name it: "commiting to switch for another branch" or "final commit for this current branch" or something like that.

**Review by darkdarcool — COMMENTED** [review]
I think you should make it one absolute color. Like colors that only we use.

**Review by Isaiah-Day — APPROVED** [review]
Looks great! I approve.

**Comment by whippingdot** [comment]
> I think you should make it one absolute color. Like colors that only we use.

Naaa...I don't think that is good.

EVERYONE, I think(because people are starting to stop working on this) we should just share the second version of this project.  The only thing is this branch has some js which is broken. I don't think it is fixed, ask @BD103. If it is fixed then we will merge and continue but if not then either fix the things, or make it so you take all necessary changes from this pr(meaning copy the files) and create a new pr. Then paste all the files with the changes into the files of the new pr, make sure everything works, and finally, we will approve changes of the other pr and we will merge. I want @BD103, @darkdarcool, and @firefish111 to mainly work on this. I am on a ban(from parents, don't ask) so I can't code(and I am not really even supposed to comment here) and so I hope you guys can do this. If not, my ban started yesterday and today is the last day so tomorrow I will help you. Please do your best to finish it by yourself tho.

**Comment by zplusfour** [comment]
> > I think you should make it one absolute color. Like colors that only we use.
> 
> Naaa...I don't think that is good.
> 
> EVERYONE, I think(because people are starting to stop working on this) we should just share the second version of this project. The only thing is this branch has some js which is broken. I don't think it is fixed, ask @BD103. If it is fixed then we will merge and continue but if not then either fix the things, or make it so you take all necessary changes from this pr(meaning copy the files) and create a new pr. Then paste all the files with the changes into the files of the new pr, make sure everything works, and finally, we will approve changes of the other pr and we will merge. I want @BD103, @darkdarcool, and @firefish111 to mainly work on this. I am on a ban(from parents, don't ask) so I can't code(and I am not really even supposed to comment here) and so I hope you guys can do this. If not, my ban started yesterday and today is the last day so tomorrow I will help you. Please do your best to finish it by yourself tho.
> 
> P.S. PLEASE remember to switch branches on the repl before making the changes. Currently we are on feature branch so change the branch before copying files, pasting files, and such. Also when changing branches if there are changes which you don't know what did the commit message should be something like "Commit to switch branches". [#6 (comment)](https://github.com/Repl-it-Coders/Repl.it-2020/pull/6#issuecomment-758033457)

Smh why ppl give bans for their kids

**Review by programmeruser2 — APPROVED** [review]
Seems fine.

**Comment by whippingdot** [comment]
> Seems fine.

@BD103 did you finish fixing it? I don't think it is **fine** yet.

---

> Smh why ppl give bans for their kids

(Silently) _You have to have a punishment, you can't hit your kids_

**Comment by whippingdot** [comment]
@zplusfour Check [this](https://dev.to/timmybytes/keeping-git-commit-messages-consistent-with-a-custom-template-1jkm) article out.

**Comment by zplusfour** [comment]
> @zplusfour Check [this](https://dev.to/timmybytes/keeping-git-commit-messages-consistent-with-a-custom-template-1jkm) article out.

Dev.to is bugging, I'll give you a screen shot:
image

**Comment by IcingHackz** [comment]
so um @ColePete u said u have covid before i even joined this org xD . now it's may (few months later when u said u tested positive :P which was jan.) u should be better already...are u?

**Review by iop3 — APPROVED** [review]
:/ ok

**Comment by BD103** [comment]
Honestly, this PR is stale. Closing.

**Comment by JBYT27** [comment]
lol

**Comment by darkdarcool** [comment]
thank you

**Comment by IcingHackz** [comment]
lmao

**Comment by whippingdot** [comment]
Lul it's been like a year

**Comment by iop3** [comment]
yOs it has @whippingdot

**Comment by firefish111** [comment]
@MrQuackDev how tf am I talking to myself

**Comment by darkdarcool** [comment]
ngl idk @firefish111

**Comment by firefish111** [comment]
@darkdarcool I used to go under the name of lord quack before I came back to replit when lockdown started. Then I stuck to the old "johnstev111" then renamed myself everywhere to the firefish during August of 2020

**Pull request closed without merging**
