### PR TITLE
Icons and Minor Updates

### PR DESCRIPTION
**Pull request by darkdarcool**
# New features.
So I with the hep with @AmazingMech2418 and @headiscoding . We were able to add a couple things. 
We added css, we fixed the repl auth. We changed the nav bar colors on every page so you know what page you are on.
We made the auth only an option. Not mandatory. 
We made it so if you did the auth that your user is auto on the name that you have to input on the suggestion page.
There are many more thing to add but we did those. 
Tell me what you think.
whippingdot will have to approve this before in is put into the feature branch. 
I hope these make the cut into the post that we will do later on repl.it
Thanks!
-darkdarcool
We made it on this repl link https://replit-2021.whippingdot.repl.co/
You can look before you give the thumbs up.

### CODE REVIEW

**Comment by AmazingMech2418** [comment]
It doesn't seem like it worked...

**Comment by darkdarcool** [comment]
Wait, who messed up the repl??
The changes are gone?
What happend????/

**Comment by AmazingMech2418** [comment]
The changes are still there...

**Comment by AmazingMech2418** [comment]
Just not in the PR.

**Comment by BD103** [comment]
Hey, this PR has the same name as another that you created. Could you rename one of them?

**Comment by BD103** [comment]
You never merged this, so I'm going to do that.

**Pull request merged**
